WiredBrainCoffee/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace WiredBrainCoffee.Models
{
    public class Contact
    {
        [Required]
        public string Name { get; set; }
        [Phone]
        [Required]
        public string Phone { get; set; }
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        [MinLength(10)]
        [Required]
        public string Message { get; set; }
    }
}

WiredBrainCoffee/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WiredBrainCoffee.Models
{
    public class MenuItem
    {
        public int Id { get; set; }
        public string Slug { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
    }
}

WiredBrainCoffee/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffee.Models;
using WiredBrainCoffee.Services;

namespace WiredBrainCoffee.Pages
{
    public class ConfirmationModel : PageModel
    {
        public string Message { get; set; }

        public void OnGetContact()
        {
            Message = "Your email was sent.";
        }


        public void OnGetSubscribe()
        {
            Message = "You have been added to the mailing list.";
        }
    }
}

WiredBrainCoffee/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffee.Models;
using WiredBrainCoffee.Services;

namespace WiredBrainCoffee.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty]
        public Contact Contact { get; set; }
        public string Message { get; private set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                EmailService.SendEmail(Contact);
                return new RedirectToPageResult("Confirmation", "Contact");
            }
            else
            return Page();
        }

        public IActionResult OnPostSubscribe(string address)
        {
            bool isValid = new EmailAddressAttribute().IsValid(address);
            if (isValid)
            {
                EmailService.SendEmail(address);
                return new RedirectToPageResult("Confirmation", "Subscribe");
            }
            else
            return Page();
        }
    }
}

WiredBrainCoffee/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffee.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WiredBrainCoffee/Pages/Feedback.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffee.Pages
{
    public class FeedbackModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

WiredBrainCoffee/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WiredBrainCoffee.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WiredBrainCoffee/Pages/Item.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffee.Models;
using WiredBrainCoffee.Services;

namespace WiredBrainCoffee.Pages
{
    public class ItemModel : PageModel
    {
        public MenuItem Item { get; private set; }

        public void OnGet(string slug)
        {
            var menuService = new MenuService();
            Item = menuService.GetMenuItems().FirstOrDefault(x => x.Slug == slug);
        }
    }
}

WiredBrainCoffee/Pages/Menu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WiredBrainCoffee.Models;
using WiredBrainCoffee.Services;

namespace WiredBrainCoffee.Pages
{
    public class MenuModel : PageModel
    {
        public List<MenuItem> MenuItems { get; set; }
        private IMenuService menuService;
        public void OnGet()
        {
            menuService = new MenuService();
            MenuItems = menuService.GetMenuItems();
        }
    }
}

WiredBrainCoffee/Pages/Offers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClub
{
    public class OffersModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WiredBrainCoffee/Pages/Confirmation.cshtml
@page
@model ConfirmationModel
@{
    ViewData["Title"] = "Contact";
}

<div class="container cont act-container">
    <h1 class="mt-4 mb-3">
        Thank you!
        <small>It's always great to hear from you..</small>
    </h1>
    <hr />
    @if (!string.IsNullOrEmpty(Model.Message)) {
        <h3>@Model.Message</h3>
    }
    <br />
    <p>If you have any further questions, you can contact us 555-123-1234.</p>
</div>

WiredBrainCoffee/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}

<div class="container">
    <h1 class="mt-4 mb-3">
        Contact
        <small>We'd love to hear from you.</small>
    </h1>
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <div class="alert alert-success">@Model.Message</div>
    }
    <div class="row">
        <div class="col-md-8 mb-4">
            <p>Life gets busy but we try to respond with 24 hours.  If you have a more immediate question, give us a ring using the number over on the right. We are crazy friendly!</p>
            <br />
            <form asp-page="Contact" method="post">
                <div class="control-group form-group">
                    <div class="controls">
                        <label asp-for="Contact.Name">Name:</label>
                        <input asp-for="Contact.Name" class="form-control"/>
                        <span asp-validation-for="Contact.Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label asp-for="Contact.Phone">Phone Number:</label>
                        <input asp-for="Contact.Phone" class="form-control" />
                        <span asp-validation-for="Contact.Phone" class="text-danger"></span>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label asp-for="Contact.Email">Email:</label>
                        <input asp-for="Contact.Email" class="form-control" />
                        <span asp-validation-for="Contact.Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label asp-for="Contact.Message">Message:</label>
                        <textarea rows="10" cols="100" asp-for="Contact.Message" class="form-control"></textarea>
                        <span asp-validation-for="Contact.Message" class="text-danger"></span>
                    </div>
                </div>
                <div id="success"></div>
                <button type="submit" class="btn btn-success" id="sendMessageButton">Send Message!</button>
            </form>
        </div>
        <div class="col-md-4">
            <div>
                <h3>Keep in Touch</h3>
                <p>Sign up for our mailing list - no spam, we promise.</p>
                <form asp-page-handler="Subscribe">
                    <div class="control-group form-group">
                        <input name="address" type="text" class="form-control" placeholder="Email" />
                    </div>
                    <div class="control-group form-group">
                        <input type="submit" class="btn btn-success" value="Join" />
                    </div>
                </form>
            </div>
            <h3>Where to find us:</h3>

            <div class="embed-responsive embed-responsive-1by1">
                <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6217.561841648514!2d-73.97107391676826!3d40.799839468555405!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2f624f81f9e47%3A0x9449f8329063c319!2sBeFitNYC!5e0!3m2!1spl!2spl!4v1579349696738!5m2!1spl!2spl" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
</div>

WiredBrainCoffee/Pages/Feedback.cshtml
@page "/thoughts/{token:alpha:minlength(5)}"
@model ContactModel

<div class="container">
    <h1 class="mt-4 mb-3">
        Feedback
        <small>Let us know how we're doing.</small>
    </h1>
    <hr />
    <div class="row">
        <div class="col-md-8 mb-4">
            <p>We care about what you thoughts and feelings - let us know how we can better serve you.</p>
            <br />
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Your Name:</label>
                        <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Email:</label>
                        <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <label><strong>Flavor</strong> - How did the beverage or food taste?</label>
                    <div class="controls">
                        <select class="form-control">
                            <option value="1">Great</option>
                            <option value="1">Good</option>
                            <option value="1">Neutral</option>
                            <option value="1">Fair</option>
                            <option value="1">Poor</option>
                        </select>
                    </div>
                </div>
                <div class="control-group form-group">
                    <label><strong>Customer Service</strong> - How well did we serve you?</label>
                    <div class="controls">
                        <select class="form-control">
                            <option value="1">Great</option>
                            <option value="1">Good</option>
                            <option value="1">Neutral</option>
                            <option value="1">Fair</option>
                            <option value="1">Poor</option>
                        </select>
                    </div>
                </div>
                <div class="control-group form-group">
                    <label><strong>Pricing</strong> - How was the value?</label>
                    <div class="controls">
                        <select class="form-control">
                            <option value="1">Great</option>
                            <option value="1">Good</option>
                            <option value="1">Neutral</option>
                            <option value="1">Fair</option>
                            <option value="1">Poor</option>
                        </select>
                    </div>
                </div>
                <div class="control-group form-group">
                    <label><strong>Cafe Presentation</strong> - How clean and inviting was the shop?</label>
                    <div class="controls">
                        <select class="form-control">
                            <option value="1">Great</option>
                            <option value="1">Good</option>
                            <option value="1">Neutral</option>
                            <option value="1">Fair</option>
                            <option value="1">Poor</option>
                        </select>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Other Feedback:</label>
                        <textarea rows="5" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                    </div>
                </div>
                <div id="success"></div>
                <button type="submit" class="btn btn-success" id="sendMessageButton">Submit Feedback</button>
            </form>
        </div>
    </div>
</div>

WiredBrainCoffee/Pages/Index.cshtml
@page
@model IndexModel

<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active" style="background-image: url('images/banner/hotel-windsor-fitness-spa-banner.jpg'); background-size: cover">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Group excercises</h3>
                    <p>For begginers and advanced</p>
                </div>
            </div>
            <div class="carousel-item" style="background-image: url('images/banner/frauen-fitness-banner.jpg'); background-position-y:top">
                <div class="carousel-caption d-none d-md-block">
                    <h3>One on one</h3>
                    <p>With best personal trainers</p>
                </div>
            </div>
            <div class="carousel-item" style="background-image: url('images/banner/men-woman-banner.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Always there for You</h3>
                    <p>Personal trainers wanting to help</p>
                </div>
            </div>
            <div class="carousel-item" style="background-image: url('images/banner/men-woman-running-banner.jpg')">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Best fitness equipment</h3>
                    <p>Simply the best.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>
<div class="container">
    <h1 class="my-4">Three options to keep your fit and healthy.</h1>
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-image bg-trainer">
                </div>
                <div class="card-body">
                    <h2 class="card-title">Train</h2>
                    <p class="card-text">A modern fitness environment designed for everyone… from first time gym goers to fitness fanatics. It's for You to choose whether to train alone or in group. But remember to choose wisely!</p>
                </div>
                <div class="card-footer">
                    <a asp-page="Offers" class="btn btn-success">Training offers</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-image bg-protein-shake">
                </div>
                <div class="card-body">
                    <h2 class="card-title">Eat</h2>
                    <p class="card-text">Discover delicious meals to aid your workout recovery and effectiveness, and get expert diet advice for better muscle gains and healthy fat loss.</p>
                </div>
                <div class="card-footer">
                    <a asp-page="Menu" class="btn btn-success" >Full Menu</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-image bg-spa">
                </div>
                <div class="card-body">
                    <h2 class="card-title">Relax</h2>
                    <p class="card-text">A dry sauna, relaxation cave, and steam sauna will certainly help you relax after a hard workout or a day on the slopes.</p>
                    <p class="card-text">Our friendly SPA will suit Your needs</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-success">Relax</a>
                </div>
            </div>
        </div>
    </div>
    <hr class="mb-5">
    <div class="row">
        @*<div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h2>Download our App</h2>
                    <div class="description">
                        <p>Stay wired on the go with these benefits:</p>
                        <ul>
                            <li>Coupons and promotions</li>
                            <li>Brainiacs club benefits</li>
                            <li>Store locator</li>
                            <li>Latest menu options</li>
                        </ul>
                    </div>
                    <img class="img-fluid rounded" src="~/images/download-small.png" alt="">
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-success">Download</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <cache expires-after="TimeSpan.FromSeconds(5)" vary-by-query="time">
                    <div class="card-body">
                        <h2 class="card-title">Popular Brews <small>as of @DateTime.Now</small></h2>
                        <p><span class="card-text text-success">Pumpkin Latte</span> - A refreshing pumpkin flavored drink, with a hint of mocha and spice. <i>350 calories</i><i> $3.49</i></p>
                        <p><span class="card-text text-success">Light Mocha</span> - All the mocha flavoring with just a few of the calories. <i>100 calories</i><i> $2.99</i></p>
                        <p><span class="card-text text-success">Vanilla Cappucino</span> - The natural sweetness of vanilla ensures minimal sugar and calories. <i>150 calories</i><i> $3.99</i></p>
                    </div>
                </cache>
                <div class="card-footer">
                    <a href="#" class="btn btn-success">Full Menu</a>
                </div>
            </div>
        </div>*@
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h2>Contact Us</h2>
                    <img style="width: 75%; margin: 0 auto; display: block;" src="~/images/placeholder.png" />
                    <p>Questions or feedback about anything? We'd love to hear from you.</p>
                </div>
                <div class="card-footer">
                    <a asp-page="Contact" class="btn btn-success">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
    <hr class="mb-5">
</div>

WiredBrainCoffee/Pages/Item.cshtml
@page "/Menu/{slug}"
@model ItemModel
@{
    ViewData["Title"] = "About";
}

<div class="container">
    <h1 class="mt-4 mb-3">
        @Model.Item.Name
    </h1>
    <hr />
    <h3>A Taste of Autumn.</h3>

    <div class="row">
        <div class="col-lg-8">
            <img class="img-fluid rounded" src="~/images/menu/@Model.Item.ImageFile" alt="">
            <hr>
            <p>Available starting at 8:00 AM</p>
            <hr>
            <p class="lead">@Model.Item.Summary</p>
            <blockquote class="blockquote">
                <p class="mb-0">I feel at home every time I take a bite.</p>
                <footer class="blockquote-footer">
                    Actual customer
                    <cite title="Source Title">Happy Customer</cite>
                </footer>
            </blockquote>
            <p>@Model.Item.Description</p>
            <hr>
        </div>
        <div class="col-md-4">
            <div class="card">
                <h5 class="card-header">Nutrition Information</h5>
                <div class="card-body">
                    <p>Note: Nutrition information is an estimate only.  We back our goods fresh every day, so nutrition values may vary depending on preparation and serving size.</p>
                    <ul>
                        <li>Calories: 300</li>
                        <li>Total Fat: 25%</li>
                        <li>Saturated Fat: 15%</li>
                        <li>Fiber: 20%</li>
                        <li>Sugar: 25g</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

WiredBrainCoffee/Pages/Menu.cshtml
@page
@model MenuModel
@{
    ViewData["Title"] = "About";
}

<div class="container">
    <h1 class="mt-4 mb-3">
        Our Menu
    </h1>
    <hr />
    <h3>Brain food, comfort food..we have it all.</h3>
    <p>Our food is made with all natural ingredients and sourced from local farms.  We're committed to sustainability!</p>
    <div class="row">
        @foreach (var item in Model.MenuItems)
        {
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href="/item"><img asp-append-version="true" class="card-img-top" src="~/images/Menu/@item.ImageFile" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a class="color-main" href="#">@item.Name</a>
                        </h4>
                        <p class="card-text">@item.Summary</p>
                    </div>
                    <div class="card-footer">
                        <a asp-page="item" asp-route-slug="@item.Slug" class="btn btn-success w-100">Details & Nutrition</a>
                    </div>
                </div>
            </div>
        }
        </div>
</div>

WiredBrainCoffee/Pages/Offers.cshtml
@page
@model FitnessClub.OffersModel
@{
    ViewData["Title"] = "Offers";
    Layout = "~/Pages/_Layout.cshtml";
}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Here You can choose between our training offers. Whatever suits You best.</p>
</div>

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">One-time entry</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$10</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>One time entry</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-primary">Sign up - first entry for free</button>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Monthly card</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$50</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>One month entry</li>
                    <li>No contract</li>
                </ul>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Anual card</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$500</h1>
                <h2 class="text-muted">or</h2>
                <h1 class="card-title pricing-card-title">42$ <small class="text-muted">/ mo</small></h1>

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Billed monthly or anually</li>
                    <li>Two months free</li>
                    <li>Simple contract</li>
                    <li>Spa centre 20% discount</li>
                </ul>
            </div>
        </div>
    </div>
</div>